#!/bin/bash

# validate at least 2 args are supplied
if [[ ( -z $1 ) || ( -z $2 ) ]]; then
    echo "Usage: ./ttycaster user@hostname:port /what/to/cast"
    exit
fi

connection="$1" # where to ssh
command="${@:2}" # what to stream

# parse connection details
user="$(echo $connection | cut -s -d '@' -f 1)"
user="${user:-$(echo $USER)}"
hostname="$(echo $connection | cut -d '@' -f 2)"
hostname="$(echo $connection | cut -d ':' -f 1)"
port="$(echo $connection | cut -s -d ':' -f 2)"
port="${port:-22}" # default ssh port

# local terminal dimensions
rows=$(stty size | cut -d ' ' -f 1)
cols=$(stty size | cut -d ' ' -f 2)
echo "Term size: $cols x $rows"

# create local named-pipe
pipe="/tmp/ttycast"
rm -f $pipe
mkfifo $pipe

# execute dlacewell/ttycast container on host
echo "Logging to $hostname:$port as $user"
sleep 3 && \
    ttyplay -n /tmp/ttycast | \
        ssh \
            -o KexAlgorithms=diffie-hellman-group1-sha1 \
            -o StrictHostKeyChecking=no \
            -o GlobalKnownHostsFile=/dev/null \
            -o UserKnownHostsFile=/dev/null \
            -p $port $hostname $rows $cols $msg &> /dev/null &

# execute local command
cd $(dirname $1) # path of command
ttyrec -e $command /tmp/ttycast
