#!/bin/bash

if [ -f /etc/ttycaster.conf ]
then
    source /etc/ttycaster.conf
fi

IFS=' ' eval 'args=($2)'
cols="${args[0]:-80}"
rows="${args[1]:-24}"
user="${args[2]:-Unknown user}"
advert="${args[@]:3}"
image="dlacewell/ttycaster"

docker run --rm \
       -i -p 80 -e PORT=80 \
       --name="$user" \
       # ttycaster index reads these
       -e NAME="$user" \
       -e ADVERT="$advert" \
       # jwilder's nginx proxy reads this
       -e VIRTUAL_HOST="$user.$HOSTNAME" \
       $image ttycast -c $cols -r $rows
